### ISSUE TITLE
Cant start the bot

### ISSUE THREAD

**Issue by Artapel** [yugecin/tsstats#2]
Good day. Thank you very much for the bot. Im like it very much and would like to use it.
I followed your instructions but i cannot seem to start the bot. 
When i run the command "`nohup java -jar tsstats.jar&`"

i get the following and the bot does not start

>  nohup java -jar tsstats.jar&
> [1] 85756
> [tsstats@localhost statistics]# nohup: ignoring input and appending output to ‘nohup.out’

I also do not have a tsstats.jar file and there is no such file in the download from github. 

What am i missing?

**Comment by yugecin** [comment]
If you don't have the .jar file, that command won't do much.
You can find it here: https://github.com/yugecin/tsstats/releases
Direct link: https://github.com/yugecin/tsstats/releases/download/1.0/tsstats.jar

**Comment by Artapel** [comment]
Thank you very much!!!
