### ISSUE TITLE
Teamspeak Viewer is empty

### ISSUE THREAD

**Issue by Artapel** [yugecin/tsstats#8]
Good day.

Do you perhaps have advice on why the last tab "Teamspeak Viewer" us empty. i only see one small icon and nothing else?

**Comment by yugecin** [comment]
check these ini settings: https://github.com/yugecin/tsstats/blob/master/tsstats.sample.ini#L42-L43

**Comment by Artapel** [comment]
mmm That is configured. This is what my line looks like

Location
[*/htdocs/statistics/hteamspeak.txt](url)

> ; dump info for the webbased viewer (see the tsstats-webviewer repo)
> enablesiteviewer: yes
> siteviewerfile:  */htdocs/statistics/hteamspeak.txt

**Comment by yugecin** [comment]
the sample uses `.hteamspeak.txt` (notice the dot), and the webviewer will look for that file by default. So I think you need to either change it to `.hteamspeak.txt` (with a dot) or change the webviewer so it looks for a file without the dot.

**Comment by Artapel** [comment]
I see. One thing i noticed is that the file does not yet exists. Neither with or without the dot. 
Can you perhaps share when the file gets created? Every 5 minutes maybe?
or where can i check the settings responsible for creating the file

**Comment by yugecin** [comment]
https://github.com/yugecin/tsstats/blob/master/src/viewer/ViewerUpdater.java#L91-L116
Check the file permissions if you're on a unix environment, perhaps check the log
